// <auto-generated />
using System;
using AMC.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMC.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527085049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AMC.Web.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ChangedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AMC.Web.Models.BillingEvent", b =>
                {
                    b.Property<int>("BillingEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("BillingPeriodFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BillingPeriodTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedByRule")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PlannedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PlannedInvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("BillingEventId");

                    b.HasIndex("ContractId");

                    b.ToTable("BillingEvents");
                });

            modelBuilder.Entity("AMC.Web.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillingCycle")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ContractAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PMCycle")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PMCycleOriginalText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PMMonthText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PMScheduleText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PONumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentContractId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentTermsOriginalText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCovered")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RenewalReminderDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RenewalYear")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceRowEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceRowStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceSheet")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ContractId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ParentContractId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("AMC.Web.Models.ContractScopeDetail", b =>
                {
                    b.Property<int>("ContractScopeDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallationYear")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSection")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WarrantyInfo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ContractScopeDetailId");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractScopeDetails");
                });

            modelBuilder.Entity("AMC.Web.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GSTNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedCustomerName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("UPPER(TRIM(REPLACE([CustomerName], '.', '')))", true);

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.HasIndex("NormalizedCustomerName", "GSTNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Customer_NormalizedName_GST")
                        .HasFilter("[CustomerName] IS NOT NULL");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AMC.Web.Models.Engineer", b =>
                {
                    b.Property<int>("EngineerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("EngineerId");

                    b.ToTable("Engineers");
                });

            modelBuilder.Entity("AMC.Web.Models.FollowUp", b =>
                {
                    b.Property<int>("FollowUpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discussion")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FollowUpDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("NextFollowUpDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("FollowUpId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("FollowUps");
                });

            modelBuilder.Entity("AMC.Web.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BillingEventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("BillingPeriodFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BillingPeriodTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InvoiceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedInvoiceNumber")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("NULLIF(UPPER(LTRIM(RTRIM([InvoiceNumber]))), '')", true);

                    b.Property<decimal?>("ReceivedAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceId");

                    b.HasIndex("BillingEventId");

                    b.HasIndex("NormalizedInvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Invoice_NormalizedInvoiceNumber")
                        .HasFilter("[NormalizedInvoiceNumber] IS NOT NULL");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("AMC.Web.Models.InvoiceRemarkHistory", b =>
                {
                    b.Property<int>("InvoiceRemarkHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemarkContext")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("RemarkDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemarkText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceColumn")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceRow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceSheet")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceRemarkHistoryId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceRemarkHistories");
                });

            modelBuilder.Entity("AMC.Web.Models.PMReport", b =>
                {
                    b.Property<int>("PMReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FileSizeKB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PMVisitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UploadedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PMReportId");

                    b.HasIndex("PMVisitId");

                    b.ToTable("PMReports");
                });

            modelBuilder.Entity("AMC.Web.Models.PMScheduleTemplate", b =>
                {
                    b.Property<int>("PMScheduleTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdvanceOrPostPM")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("AnchorDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CycleCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CycleIntervalMonths")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("OriginalRuleText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("PMScheduleTemplateId");

                    b.HasIndex("ContractId");

                    b.ToTable("PMScheduleTemplates");
                });

            modelBuilder.Entity("AMC.Web.Models.PMVisit", b =>
                {
                    b.Property<int>("PMVisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EngineerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleSource")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitRemarks")
                        .HasColumnType("TEXT");

                    b.HasKey("PMVisitId");

                    b.HasIndex("ContractId");

                    b.HasIndex("EngineerId");

                    b.ToTable("PMVisits");
                });

            modelBuilder.Entity("AMC.Web.Models.BillingEvent", b =>
                {
                    b.HasOne("AMC.Web.Models.Contract", "Contract")
                        .WithMany("BillingEvents")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BillingEvent_Contract");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AMC.Web.Models.Contract", b =>
                {
                    b.HasOne("AMC.Web.Models.Customer", "Customer")
                        .WithMany("Contracts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Contract_Customer");

                    b.HasOne("AMC.Web.Models.Contract", "ParentContract")
                        .WithMany("ChildContracts")
                        .HasForeignKey("ParentContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Contract_Parent");

                    b.Navigation("Customer");

                    b.Navigation("ParentContract");
                });

            modelBuilder.Entity("AMC.Web.Models.ContractScopeDetail", b =>
                {
                    b.HasOne("AMC.Web.Models.Contract", "Contract")
                        .WithMany("ContractScopeDetails")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ContractScopeDetail_Contract");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AMC.Web.Models.FollowUp", b =>
                {
                    b.HasOne("AMC.Web.Models.Invoice", "Invoice")
                        .WithMany("FollowUps")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FollowUp_Invoice");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("AMC.Web.Models.Invoice", b =>
                {
                    b.HasOne("AMC.Web.Models.BillingEvent", "BillingEvent")
                        .WithMany("Invoices")
                        .HasForeignKey("BillingEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BillingEvent");
                });

            modelBuilder.Entity("AMC.Web.Models.InvoiceRemarkHistory", b =>
                {
                    b.HasOne("AMC.Web.Models.Invoice", "Invoice")
                        .WithMany("InvoiceRemarkHistories")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceRemarkHistory_Invoice");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("AMC.Web.Models.PMReport", b =>
                {
                    b.HasOne("AMC.Web.Models.PMVisit", "PMVisit")
                        .WithMany("PMReports")
                        .HasForeignKey("PMVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PMReport_PMVisit");

                    b.Navigation("PMVisit");
                });

            modelBuilder.Entity("AMC.Web.Models.PMScheduleTemplate", b =>
                {
                    b.HasOne("AMC.Web.Models.Contract", "Contract")
                        .WithMany("PMScheduleTemplates")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PMScheduleTemplate_Contract");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AMC.Web.Models.PMVisit", b =>
                {
                    b.HasOne("AMC.Web.Models.Contract", "Contract")
                        .WithMany("PMVisits")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PMVisit_Contract");

                    b.HasOne("AMC.Web.Models.Engineer", "Engineer")
                        .WithMany("PMVisits")
                        .HasForeignKey("EngineerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_PMVisit_Engineer");

                    b.Navigation("Contract");

                    b.Navigation("Engineer");
                });

            modelBuilder.Entity("AMC.Web.Models.BillingEvent", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("AMC.Web.Models.Contract", b =>
                {
                    b.Navigation("BillingEvents");

                    b.Navigation("ChildContracts");

                    b.Navigation("ContractScopeDetails");

                    b.Navigation("PMScheduleTemplates");

                    b.Navigation("PMVisits");
                });

            modelBuilder.Entity("AMC.Web.Models.Customer", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("AMC.Web.Models.Engineer", b =>
                {
                    b.Navigation("PMVisits");
                });

            modelBuilder.Entity("AMC.Web.Models.Invoice", b =>
                {
                    b.Navigation("FollowUps");

                    b.Navigation("InvoiceRemarkHistories");
                });

            modelBuilder.Entity("AMC.Web.Models.PMVisit", b =>
                {
                    b.Navigation("PMReports");
                });
#pragma warning restore 612, 618
        }
    }
}
